In [2]:
import sys
sys.path.append('/home/mohilbajaj2002/anaconda3/envs/fleetnews/lib/python3.6/site-packages')

In [21]:
import pandas as pd
import numpy as np
import googlemaps
import time

In [6]:
api_key = '********************************'  # Enter your own key here

In [7]:
gm = googlemaps.Client(key = api_key)
geocode_result = gm.geocode('174 ANG MO KIO AVE 4')

In [13]:
geocode_result[0]

{'address_components': [{'long_name': 'Block 174',
   'short_name': 'Block 174',
   'types': ['premise']},
  {'long_name': '174', 'short_name': '174', 'types': ['street_number']},
  {'long_name': 'Ang Mo Kio Avenue 4',
   'short_name': 'Ang Mo Kio Ave 4',
   'types': ['route']},
  {'long_name': 'Ang Mo Kio',
   'short_name': 'Ang Mo Kio',
   'types': ['neighborhood', 'political']},
  {'long_name': 'Singapore',
   'short_name': 'Singapore',
   'types': ['locality', 'political']},
  {'long_name': 'Singapore',
   'short_name': 'SG',
   'types': ['country', 'political']},
  {'long_name': '560174', 'short_name': '560174', 'types': ['postal_code']}],
 'formatted_address': '174 Ang Mo Kio Ave 4, Block 174, Singapore 560174',
 'geometry': {'bounds': {'northeast': {'lat': 1.375638, 'lng': 103.837917},
   'southwest': {'lat': 1.3751121, 'lng': 103.8370078}},
  'location': {'lat': 1.3752431, 'lng': 103.8374311},
  'location_type': 'ROOFTOP',
  'viewport': {'northeast': {'lat': 1.376724030291502,
    'lng': 103.8388113802915},
   'southwest': {'lat': 1.374026069708498, 'lng': 103.8361134197085}}},
 'place_id': 'ChIJT0jv8sQW2jER2-N98Xpdz6U',
 'types': ['premise']}

In [20]:
geocode_result[0]['geometry']['location']

{'lat': 1.3752431, 'lng': 103.8374311}

# Getting lats and longs for HDB Blocks

In [23]:
df = pd.read_csv('resale-flat-prices/resale-flat-prices-based-on-registration-date-from-jan-2015-onwards.csv')
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2015-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,07 TO 09,60.0,Improved,1986,70,255000.0
1,2015-01,ANG MO KIO,3 ROOM,541,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1981,65,275000.0
2,2015-01,ANG MO KIO,3 ROOM,163,ANG MO KIO AVE 4,01 TO 03,69.0,New Generation,1980,64,285000.0
3,2015-01,ANG MO KIO,3 ROOM,446,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1979,63,290000.0
4,2015-01,ANG MO KIO,3 ROOM,557,ANG MO KIO AVE 10,07 TO 09,68.0,New Generation,1980,64,290000.0

In [24]:
df['full_address'] = df.block + ' ' + df.street_name + ' Singapore'
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,full_address
0,2015-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,07 TO 09,60.0,Improved,1986,70,255000.0,174 ANG MO KIO AVE 4 Singapore
1,2015-01,ANG MO KIO,3 ROOM,541,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1981,65,275000.0,541 ANG MO KIO AVE 10 Singapore
2,2015-01,ANG MO KIO,3 ROOM,163,ANG MO KIO AVE 4,01 TO 03,69.0,New Generation,1980,64,285000.0,163 ANG MO KIO AVE 4 Singapore
3,2015-01,ANG MO KIO,3 ROOM,446,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1979,63,290000.0,446 ANG MO KIO AVE 10 Singapore
4,2015-01,ANG MO KIO,3 ROOM,557,ANG MO KIO AVE 10,07 TO 09,68.0,New Generation,1980,64,290000.0,557 ANG MO KIO AVE 10 Singapore

In [25]:
uni = df.full_address.unique()
uni

array(['174 ANG MO KIO AVE 4 Singapore',
       '541 ANG MO KIO AVE 10 Singapore',
       '163 ANG MO KIO AVE 4 Singapore', ...,
       '887A WOODLANDS DR 50 Singapore', '505 WOODLANDS DR 14 Singapore',
       '779 YISHUN AVE 2 Singapore'], dtype=object)

In [27]:
uni[0]

'174 ANG MO KIO AVE 4 Singapore'

In [30]:
block_loc = pd.DataFrame()
block_loc['full_address'] = uni

for i in range (0,len(block_loc)):
    geocode_result = gm.geocode(block_loc.loc[i,'full_address'])[0]
    block_loc.loc[i,'latitude'] = geocode_result['geometry']['location']['lat']
    block_loc.loc[i,'longitude'] = geocode_result['geometry']['location']['lng']
    time.sleep(0.04)
    
block_loc.head()

                      full_address  latitude   longitude
0   174 ANG MO KIO AVE 4 Singapore  1.375243  103.837431
1  541 ANG MO KIO AVE 10 Singapore  1.373289  103.856082
2   163 ANG MO KIO AVE 4 Singapore  1.373993  103.838246
3  446 ANG MO KIO AVE 10 Singapore  1.367812  103.855186
4  557 ANG MO KIO AVE 10 Singapore  1.371606  103.857722

In [31]:
block_loc.to_csv('hdb_blocks_location.csv')

# Getting lats and longs for Spore Primary schools

In [32]:
schools = ['Anderson Primary School 19 Ang Mo Kio Avenue 9 Singapore 569785', 
          'Ang Mo Kio Primary School 20 Ang Mo Kio Avenue 3 Singapore 569920',
          'CHIJ St. Nicholas Girls School 501 Ang Mo Kio Street 13 Singapore 569405',
          'Jing Shan Primary School 5 Ang Mo Kio Street 52 Singapore 569228',
          'Mayflower Primary School 00 Ang Mo Kio Avenue 5 Singapore 569878',
          'Teck Ghee Primary School 1 Ang Mo Kio Street 32 Singapore 569299',
          'Townsville Primary School No. 3 Ang Mo Kio Avenue 10 Singapore 569730',
          'Bedok Green Primary School No. 1, Bedok South Ave 2 Singapore 469317',
          'CHIJ (Katong) Primary School 17 Martia Road, Singapore 424821',
          'Damai Primary School 52 Bedok Reservoir Crescent, Singapore 479226',
          'Fengshan Primary School 307, Bedok North Road Singapore 469680',
          'Opera Estate Primary School 48 Fidelio Street Singapore 458436',
          'Red Swastika School 350 Bedok North Avenue 3 Singapore 469719',
          'St Anthony’s Canossian Primary School 1602 Bedok North Avenue 4, Singapore 469701',
          'St Stephen’s School 20 Siglap View, Singapore 455789',
          'Telok Kurau Primary School, 50 Bedok Reservoir Rd Singapore 479239',
          'Temasek Primary School 501 Bedok South Avenue 3 Singapore 469300',
          'Yu Neng Primary School 56 Bedok North Street 3 Singapore 469623',
          'Ai Tong School - 100 Bright Hill Drive Singapore 579646',
          'Catholic High School 9 Bishan Street 22, Singapore 579767',
          'Guangyang Primary School 6 Bishan Street 12, Singapore 579806',
           'Kuo Chuan Presbyterian Primary School 8 Bishan Street 13 Singapore 579793',
          'Bukit View Primary School  18 Bukit Batok St 21 Singapore 659634',
          'Dazhong Primary School 35, Bukit Batok Street 31 Singapore 659441',
          'Keming Primary School 90 BUKIT BATOK EAST AVENUE 6 Singapore 659762',
          'Lianhua Primary School 2 Bukit Batok Street 52 Singapore 659243',
          'Princess Elizabeth Primary School 30 Bukit Batok West Avenue 3 Singapore 659163',
          'St Anthony’s Primary School 30 Bukit Batok St. 32, Singapore 659401',
          'Alexandra Primary School 2A Prince Charles Crescent Singapore 159016',
          'Blangah Rise Primary School 91 Telok Blangah Heights, Singapore 109100',
          'Cantonment Primary School 1 Cantonment Close Singapore 088256',
          'CHIJ (Kellock) 121 Queensway 149059',
          'Gan Eng Seng Primary School 100 Redhill Cl, Singapore 158901',
          'Radin Mas Primary School 1 Bukit Purmei Avenue Singapore 099840',
          'Zhangde Primary School 51 Jln Membina, Singapore 169485',
          'Beacon Primary School 36, Bukit Panjang Ring Road Singapore 679944',
          'Bukit Panjang Primary School 109 Cashew Road Singapore 679676',
          'CHIJ (Our Lady Queen of Peace) 4 Chestnut Drive Singapore 679287',
          'Greenridge Primary School 11 Jelapang Road Singapore 677744',
          'West Spring Primary School 60 Bukit Panjang Ring Road Singapore 679946',
          'West View Primary School 31 Senja Road Singapore 677742',
          'Zhenghua Primary School 9 Fajar Road Singapore 679002',
          'Bukit Timah Primary School 111 Lorong Kismis Singapore 598112',
          'Henry Park Primary School 1 Holland Grove Road Singapore 278790',
          'Methodist Girls’ School (Primary) 11 Blackmore Drive, Singapore 599986',
          'Nanyang Primary School 52 Kings Road Singapore 268097',
          'Pei Hwa Presbyterian Primary School 7 Pei Wah Avenue Singapore 597610',
          'Pei Hwa Presbyterian Primary School 21 Hillcrest Road Singapore 289072',
          'ACS Junior 16 Winstedt Rd, Singapore 227988',
          'River Valley Primary School 2 River Valley Green, Singapore 237993',
          'St Margaret’s Primary School 99 Wilkie Road Singapore 228091',
          'Stamford Primary School 1 Victoria Lane Singapore 198423',
          'CHUA CHU KANG PRIMARY SCHOOL 20 CHOA CHU KANG AVENUE 2 Singapore 689905',
          'Concord Primary School 3 Choa Chu Kang Ave 4 Singapore 689814',
          'De La Salle School, 11 Choa Chu Kang Street 52, Singapore 689285',
          'Kranji Primary School 11 Choa Chu Kang Street 54 Singapore 689189',
          'South View Primary School 6 Choa chu kang central Singapore 689762',
          'Teck Whye Primary School 11 Teck Whye Walk Singapore 688261',
          'Unity Primary School 21 Choa Chu Kang Crescent Singapore 688268',
          'YEW TEE PRIMARY SCHOOL 10 Choa Chu Kang Street 64, Singapore 689100',
          'Clementi Primary School 8 Clementi Ave 3 Singapore 129903',
          'Nan Hua Primary School 170 West Coast Road Singapore 127443',
          'Pei Tong Primary School 15 Clementi Ave 5 Singapore 129857',
          'Qifa Primary School 50 West Coast Avenue Singapore 128104',
          'Canossa Catholic Primary School 1 Sallim Road S387621',
          'Eunos Primary School 95 Jalan Eunos Singapore 419529',
          'Geylang Methodist School (Primary) 4 Geylang East Central Singapore 389706',
          'Haig Girls’ School 51 Koon Seng Road Singapore 427072',
          'Kong Hwa School, 350 Guillemard Road Singapore 399772',
          'MAHA BODHI SCHOOL 10 UBI AVENUE 1 Singapore 408931',
          'CHIJ Our Lady of the Nativity 1257 Upper Serangoon Road Singapore 534793',
          'Holy Innocents’ Primary School 4300 Ang Mo Kio Avenue 5 Singapore 569869',
          'Hougang Primary School 1 Hougang Street 93 Singapore 534238',
          'Montfort Junior School 52 Hougang Ave 8, Singapore 538786',
          'Paya Lebar Methodist Girls’ School (Primary) 298 Lorong Ah Soo, Singapore 536741',
          'Punggol Primary School 61 Hougang Avenue 8 Singapore 538787',
          'Xinghua Primary School 45 Hougang Avenue 1 Singapore 538882',
          'Xinmin Primary School 9 Hougang Avenue 8 Singapore 538784',
          'Yio Chu Kang Primary School No.1 Hougang Street 51 Singapore 538720',
          'Fuhua Primary School 65 Jurong East Street 13 Singapore 609647',
          'Jurong Primary School 320 Jurong East Street 32, Singapore 609476',
          'Yuhua Primary School 158 Jurong East Street 24 609558',
          'Boon Lay Garden Primary School 20 Boon Lay Drive Singapore 649930',
          'Corporation Primary School 31 Jurong West Street 24 Singapore 648347',
          'Frontier Primary School 20 Jurong West Street 61, Singapore 648200',
          'Jurong West Primary School 30 JURONG WEST ST 61  Singapore 648368 ',
          'Juying Primary School 31 Jurong West Street 91 Singapore 649037',
          'Lakeside Primary School 161 Corporation Walk Singapore 618310',
          'Pioneer Primary School 23 Jurong West Street 81 Singapore 649076',
          'Rulang Primary School 6 Jurong West St 52 Singapore 649295',
          'Shuqun Primary School 8 Jurong West Street 51 Singapore 649332',
          'West Grove Primary School 1 Jurong West Street 72 Singapore 649223',
          'Westwood Primary School 1 Jurong West Street 73 Singapore 649188',
          'Xingnan Primary School 5 Jurong West Street 91 Singapore 649036',
          'Bendemeer Primary School 91 Bendemeer Road Singapore 339948',
          'Farrer Park Primary School 2 Farrer Park Rd, Singapore 217567',
          'Hong Wen School 30 Towner Road Singapore 327829',
          'Ngee Ann Primary School 344 Marine Terrace Singapore 449149',
          'Tanjong Katong Primary School 860, New Upper Changi Road Singapore 467353',
          'Tao Nan School 49 Marine Crescent Singapore 449761',
          'Anglo-Chinese School (Primary) 50 Barker Road Singapore 309918',
          'St Josephs Institution Junior No. 3 Essex Road, Singapore 309331',
          'Singapore Chinese Girls’ School (Primary) 60 Dunearn Road, Singapore 309434',
          'Casuarina Primary School 30 Pasir Ris Street 41 Singapore 518935',
          'Elias Park Primary School 11 Pasir Ris Street 52 Singapore 518866',
          'Meridian Primary School 20 Pasir Ris Street 71 Singapore 518798',
          'PARK VIEW PRIMARY SCHOOL 60 PASIR RIS DRIVE 1 Singapore 519524',
          'Pasir Ris Primary School 5 Pasir Ris Street 21 Singapore 518968',
          'White Sands Primary School 2 Pasir Ris Street 11 Singapore 519075',
          'Edgefield Primary School 41 Edgefield Plains Singapore 828869',
          'Greendale Primary School 50 Edgedale Plains Singapore 828848',
          'Horizon Primary School 61 Edgedale Plains Singapore 828819',
          'Mee Toh School 21 Edgedale Plains Singapore 828867',
          'Oasis Primary School 71 Edgefield Plains Singapore 828716',
           'Punggol Cove Primary School 52 Sumang Walk Singapore 828674',
           'Punggol Green Primary School 98 Punggol Walk Singapore 828772',
           'Punggol View Primary School 9, Punggol Place Singapore 828845',
           'Waterway Primary School 70 Punggol Drive Singapore 828802',
           'Fairfield Methodist School (Primary) 100 Dover Road Singapore 139648',
           'New Town Primary School 300 Tanglin Halt Road Singapore 148812',
           'Queenstown Primary School 310 Margaret Drive Singapore 149303',
           'Canberra Primary School 21 Admiralty Drive Singapore 757714',
           'Endeavour Primary School 10 Admiralty Link Singapore 757521',
           'Northoaks Primary School 61 Sembawang Drive Singapore 757622',
           'Sembawang Primary School 10 Sembawang Drive Singapore 757715',
           'Wellington Primary School 10 Wellington Circle Singapore 757702',
           'Anchor Green Primary School 31 Anchorvale Drive Singapore 544969',
           'Compassvale Primary School 21 Compassvale Street Singapore 545091',
           'Fern Green Primary School 70 Fernvale Link, Singapore 797538',
           'Fernvale Primary School 1 Fernvale Lane Singapore 797701',
           'Nan Chiau Primary School 50 Anchorvale Link, Singapore 545080',
           'North Spring Primary School 1 Rivervale Street Singapore 545088',
           'North Vista Primary School 20 Compassvale Link Singapore 544974',
           'Palm View Primary School 150 Compassvale Bow Singapore 544822',
           'Rivervale Primary School 80 RIVERVALE DRIVE SINGAPORE 545092',
           'Seng Kang Primary School 21 Compassvale Walk Singapore 545166',
           'Sengkang Green Primary School 15 Fernvale Road Singapore 797636',
           'SPRINGDALE PRIMARY SCHOOL 71 Anchorvale Link Singapore 544799',
           'CHIJ (Our Lady of Good Counsel) 2C Burghley Drive Singapore 558979',
           'Rosyth School 21 Serangoon North Ave 4, Singapore 555855',
           'St Gabriel’s Primary School 220 Lorong Chuan Singapore 556742',
           'Yangzheng Primary School 15 Serangoon Avenue 3 Singapore 556108',
           'Zhonghua Primary School 12 Serangoon Ave 4 Singapore 556095',
           'Angsana Primary School 3 Tampines Street 22 Singapore 529366',
           'Changkat Primary School 11 Simei Street 3 Singapore 529896',
           'Chongzheng Primary School 1 Tampines Street 21 Singapore 529392',
           'East Spring Primary School 31 Tampines Street 33 Singapore 529258',
           'Gongshang Primary School 1 Tampines Street 42 Singapore 529176',
           'Junyuan Primary School 2 Tampines Street 91 Singapore 528906',
           'Poi Ching School 21 Tampines Street 71, Singapore 529067',
           'St. Hildas Primary School 2 Tampines Avenue 3 Singapore 529706',
           'Tampines Primary School 250 Tampines Street 12 Singapore 529426',
           'Tampines North Primary School 30 Tampines Avenue 9 Singapore 529565',
           'Yumin Primary School 3 Tampines Street 21 Singapore 529393',
           'CEDAR PRIMARY SCHOOL 15, Cedar Avenue, Singapore 349700',
           'Convent of the Holy Infant Jesus Primary (Toa Payoh) 628 Lorong 1 Toa Payoh Singapore 319765',
           'First Toa Payoh Primary School 7 Lorong 8 Toa Payoh Singapore 319252',
           'Kheng Cheng School 15 Lorong 3 Toa Payoh, Singapore 319580',
           'Maris Stella High (Primary) School 25 Mount Vernon Road Singapore 368051',
           'Marymount Convent School 20 Marymount Road Singapore 297754',
           'Pei Chun Public School 580 Toa Payoh East Singapore 319133',
           'St Andrews Junior School 2 Francis Thomas Drive Singapore 359337',
           'ADMIRALTY PRIMARY SCHOOL 11, Woodlands Circle, Singapore 738907',
           'Evergreen Primary School 31 Woodlands Circle Singapore 738908',
           'Fuchun Primary School  23 Woodlands Avenue 1 Singapore 739063',
           'Greenwood Primary School 11 Woodlands Drive 62 Singapore 737942',
           'Innova Primary School 80 Woodlands Drive 17 Singapore 737888',
           'Marsiling Primary School 31 Woodlands Centre Rd Singapore 738927',
           'Qihua Primary School 5 Woodlands Street 81 Singapore 738525',
           'RIVERSIDE PRIMARY SCHOOL 110 Woodlands Crescent Singapore 737803',
           'Si Ling Primary School 61 Woodlands Avenue 1 Singapore 739067',
           'Woodgrove Primary School 2 Woodlands Drive 14 Singapore 738079',
           'Woodlands Primary School 10 Woodlands Drive 50 Singapore 738853', 
           'Woodlands Ring Primary School 11 Woodlands Ring Road Singapore 738240',
           'Ahmad Ibrahim Primary School 10 Yishun St 11 Singapore 768643',
           'Chongfu School 170 Yishun Avenue 6 Singapore 768959',
           'Huamin Primary School 530 Yishun Ring Road Singapore 768680',
           'Jiemin Primary School No. 2 Yishun Street 71 Singapore 768515',
           'Naval Base Primary School 7 Yishun Ave 4 S769028',
           'Northland Primary School 15 Yishun Ave 4 Singapore 769026',
           'North View Primary School 210 Yishun Avenue 6 Singapore 768960',
           'Peiying Primary School 651 Yishun Ring Road Singapore 768687',
           'Xishan Primary School 8 Yishun Street 21 Singapore 768611',
           'Yishun Primary School 500 Yishun Ring Road Singapore 768679'
           
]

In [33]:
geocode_result = gm.geocode(schools[0])
geocode_result

[{'address_components': [{'long_name': '19',
    'short_name': '19',
    'types': ['street_number']},
   {'long_name': 'Ang Mo Kio Avenue 9',
    'short_name': 'Ang Mo Kio Ave 9',
    'types': ['route']},
   {'long_name': 'Ang Mo Kio',
    'short_name': 'Ang Mo Kio',
    'types': ['neighborhood', 'political']},
   {'long_name': 'Singapore',
    'short_name': 'Singapore',
    'types': ['locality', 'political']},
   {'long_name': 'Singapore',
    'short_name': 'SG',
    'types': ['country', 'political']},
   {'long_name': '569785', 'short_name': '569785', 'types': ['postal_code']}],
  'formatted_address': '19 Ang Mo Kio Ave 9, Singapore 569785',
  'geometry': {'location': {'lat': 1.384692, 'lng': 103.841225},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 1.386040980291502,
     'lng': 103.8425739802915},
    'southwest': {'lat': 1.383343019708498, 'lng': 103.8398760197085}}},
  'place_id': 'ChIJESsvBb8W2jERMTcyzgugKPc',
  'plus_code': {'compound_code': '9RMR+VF Singapore',
   'global_code': '6PH59RMR+VF'},
  'types': ['establishment', 'point_of_interest', 'school']}]

In [36]:
school_data = pd.DataFrame()
school_data['full_address'] = schools

for i in range (0,len(school_data)):
    geocode_result = gm.geocode(school_data.loc[i,'full_address'])[0]
    school_data.loc[i,'latitude'] = geocode_result['geometry']['location']['lat']
    school_data.loc[i,'longitude'] = geocode_result['geometry']['location']['lng']
    time.sleep(0.04)
    
school_data.head()

                                        full_address  latitude   longitude
0  Anderson Primary School 19 Ang Mo Kio Avenue 9...  1.384692  103.841225
1  Ang Mo Kio Primary School 20 Ang Mo Kio Avenue...  1.369347  103.839815
2  CHIJ St. Nicholas Girls School 501 Ang Mo Kio ...  1.374373  103.834216
3  Jing Shan Primary School 5 Ang Mo Kio Street 5...  1.372326  103.851713
4  Mayflower Primary School 00 Ang Mo Kio Avenue ...  1.376395  103.843181

In [37]:
disable_friendly = ['CHIJ St. Nicholas Girls School 501 Ang Mo Kio Street 13 Singapore 569405',
                   'Teck Ghee Primary School 1 Ang Mo Kio Street 32 Singapore 569299',
                   'Damai Primary School 52 Bedok Reservoir Crescent, Singapore 479226',
                   'Fengshan Primary School 307, Bedok North Road Singapore 469680',
                   'St Anthony’s Canossian Primary School 1602 Bedok North Avenue 4, Singapore 469701',
                   'Temasek Primary School 501 Bedok South Avenue 3 Singapore 469300',
                   'Yu Neng Primary School 56 Bedok North Street 3 Singapore 469623',
                   'Guangyang Primary School 6 Bishan Street 12, Singapore 579806',
                   'Dazhong Primary School 35, Bukit Batok Street 31 Singapore 659441',
                   'Alexandra Primary School 2A Prince Charles Crescent Singapore 159016',
                   'Cantonment Primary School 1 Cantonment Close Singapore 088256',
                   'West Spring Primary School 60 Bukit Panjang Ring Road Singapore 679946',
                   'Bukit Timah Primary School 111 Lorong Kismis Singapore 598112',
                   'Methodist Girls’ School (Primary) 11 Blackmore Drive, Singapore 599986',
                   'River Valley Primary School 2 River Valley Green, Singapore 237993',
                   'Stamford Primary School 1 Victoria Lane Singapore 198423',
                   'CHUA CHU KANG PRIMARY SCHOOL 20 CHOA CHU KANG AVENUE 2 Singapore 689905',
                   'De La Salle School, 11 Choa Chu Kang Street 52, Singapore 689285',
                   'Kong Hwa School, 350 Guillemard Road Singapore 399772',
                   'MAHA BODHI SCHOOL 10 UBI AVENUE 1 Singapore 408931',
                   'Punggol Primary School 61 Hougang Avenue 8 Singapore 538787',
                   'Xinghua Primary School 45 Hougang Avenue 1 Singapore 538882',
                   'Frontier Primary School 20 Jurong West Street 61, Singapore 648200',
                   'Pioneer Primary School 23 Jurong West Street 81 Singapore 649076',
                   'Shuqun Primary School 8 Jurong West Street 51 Singapore 649332',
                   'Westwood Primary School 1 Jurong West Street 73 Singapore 649188',
                   'Bendemeer Primary School 91 Bendemeer Road Singapore 339948',
                   'Tanjong Katong Primary School 860, New Upper Changi Road Singapore 467353',
                   'Elias Park Primary School 11 Pasir Ris Street 52 Singapore 518866',
                   'Edgefield Primary School 41 Edgefield Plains Singapore 828869',
                   'Horizon Primary School 61 Edgedale Plains Singapore 828819',
                   'Oasis Primary School 71 Edgefield Plains Singapore 828716',
                   'Punggol Cove Primary School 52 Sumang Walk Singapore 828674',
                   'Punggol Green Primary School 98 Punggol Walk Singapore 828772',
                   'Punggol View Primary School 9, Punggol Place Singapore 828845',
                   'Waterway Primary School 70 Punggol Drive Singapore 828802',
                   'Queenstown Primary School 310 Margaret Drive Singapore 149303',
                   'Canberra Primary School 21 Admiralty Drive Singapore 757714',
                   'Northoaks Primary School 61 Sembawang Drive Singapore 757622',
                   'Sembawang Primary School 10 Sembawang Drive Singapore 757715',
                   'Compassvale Primary School 21 Compassvale Street Singapore 545091',
                   'Fern Green Primary School 70 Fernvale Link, Singapore 797538',
                   'Nan Chiau Primary School 50 Anchorvale Link, Singapore 545080',
                   'Palm View Primary School 150 Compassvale Bow Singapore 544822',
                   'Seng Kang Primary School 21 Compassvale Walk Singapore 545166',
                   'Sengkang Green Primary School 15 Fernvale Road Singapore 797636',
                   'SPRINGDALE PRIMARY SCHOOL 71 Anchorvale Link Singapore 544799',
                   'Zhonghua Primary School 12 Serangoon Ave 4 Singapore 556095',
                   'Tampines Primary School 250 Tampines Street 12 Singapore 529426',
                   'Tampines North Primary School 30 Tampines Avenue 9 Singapore 529565',
                   'First Toa Payoh Primary School 7 Lorong 8 Toa Payoh Singapore 319252',
                   'Marymount Convent School 20 Marymount Road Singapore 297754',
                   'Evergreen Primary School 31 Woodlands Circle Singapore 738908',
                   'Marsiling Primary School 31 Woodlands Centre Rd Singapore 738927',
                   'RIVERSIDE PRIMARY SCHOOL 110 Woodlands Crescent Singapore 737803',
                   'Ahmad Ibrahim Primary School 10 Yishun St 11 Singapore 768643',
                   'Naval Base Primary School 7 Yishun Ave 4 S769028',
                   'North View Primary School 210 Yishun Avenue 6 Singapore 768960',
                   'Xishan Primary School 8 Yishun Street 21 Singapore 768611'
                   ]

In [39]:
for i in range(0,len(school_data)):
    for j in range (0,len(disable_friendly)):
        if (school_data.loc[i,'full_address'] == disable_friendly[j]):
            school_data.loc[i,'Special_Needs_Fac_Availability'] = 'Yes'
    
school_data['Special_Needs_Fac_Availability'].fillna('No')
    
school_data.head()

,full_address,latitude,longitude,Special_Needs_Fac_Availability
0,Anderson Primary School 19 Ang Mo Kio Avenue 9...,1.384692,103.841225,NaN
1,Ang Mo Kio Primary School 20 Ang Mo Kio Avenue...,1.369347,103.839815,NaN
2,CHIJ St. Nicholas Girls School 501 Ang Mo Kio ...,1.374373,103.834216,Yes
3,Jing Shan Primary School 5 Ang Mo Kio Street 5...,1.372326,103.851713,NaN
4,Mayflower Primary School 00 Ang Mo Kio Avenue ...,1.376395,103.843181,NaN

In [42]:
school_data = school_data.replace(np.nan, 'No')
school_data.head()

,full_address,latitude,longitude,Special_Needs_Fac_Availability
0,Anderson Primary School 19 Ang Mo Kio Avenue 9...,1.384692,103.841225,No
1,Ang Mo Kio Primary School 20 Ang Mo Kio Avenue...,1.369347,103.839815,No
2,CHIJ St. Nicholas Girls School 501 Ang Mo Kio ...,1.374373,103.834216,Yes
3,Jing Shan Primary School 5 Ang Mo Kio Street 5...,1.372326,103.851713,No
4,Mayflower Primary School 00 Ang Mo Kio Avenue ...,1.376395,103.843181,No

In [43]:
school_data.to_csv('primary_schools_data.csv')

# Extracting MRT Geolocation data

In [48]:
import xml.etree.ElementTree as ET
filePath = r'G_MP08_ACT_MRT_STN_PT.kml'
tree = ET.parse(filePath) 
lineStrings = tree.findall('Point')

print(lineStrings)
for attributes in lineStrings:
    for subAttribute in attributes:
        if subAttribute.tag == 'coordinates':
            print (subAttribute.tag, subAttribute.text)

[]

In [61]:
from bs4 import BeautifulSoup as bs

with open('G_MP08_ACT_MRT_STN_PT.kml') as data:
    kml_soup = bs(data, 'lxml-xml') # Parse as XML

lat = []
long = []

descriptions = kml_soup.find_all('Point')
for d in descriptions:
    coord = d.find_all('coordinates')
    for c in coord:
        values = c.text.split(',')
        latitude = values[1]
        longitude = values[0]
        lat.append(latitude)
        long.append(longitude)
   
print (len(lat),len(long))

20 20

In [62]:
mrt = pd.read_csv('train-station-chinese-names.csv')
mrt.head()

,stn_code,mrt_station_english,mrt_station_chinese,mrt_line_english,mrt_line_chinese
0,NS1,Jurong East,裕廊东,North South Line,南北线
1,NS2,Bukit Batok,武吉巴督,North South Line,南北线
2,NS3,Bukit Gombak,武吉甘柏,North South Line,南北线
3,NS4,Choa Chu Kang,蔡厝港,North South Line,南北线
4,NS5,Yew Tee,油池,North South Line,南北线

In [76]:
for i in range(0,len(mrt)):
    mrt.loc[i,'mrt_station_english'] = mrt.loc[i,'mrt_station_english'] + ' Singapore'
    
mrt.head()

,stn_code,mrt_station_english,mrt_station_chinese,mrt_line_english,mrt_line_chinese,latitude,longitude
0,NS1,Jurong East MRT Station Singapore,裕廊东,North South Line,南北线,1.333131,103.742091
1,NS2,Bukit Batok MRT Station Singapore,武吉巴督,North South Line,南北线,1.348506,103.749222
2,NS3,Bukit Gombak MRT Station Singapore,武吉甘柏,North South Line,南北线,1.358915,103.751831
3,NS4,Choa Chu Kang MRT Station Singapore,蔡厝港,North South Line,南北线,1.385385,103.744337
4,NS5,Yew Tee MRT Station Singapore,油池,North South Line,南北线,1.397329,103.747502

In [77]:
for i in range (0,len(mrt)):
    try:
        geocode_result = gm.geocode(mrt.loc[i,'mrt_station_english'])[0]
        mrt.loc[i,'latitude'] = geocode_result['geometry']['location']['lat']
        mrt.loc[i,'longitude'] = geocode_result['geometry']['location']['lng']
        time.sleep(0.04)
    except:
        mrt.loc[i,'latitude'] = 0
        mrt.loc[i,'longitude'] = 0
        
mrt = mrt.drop(['mrt_station_chinese','mrt_line_chinese'], axis = 1)
mrt.head()

,stn_code,mrt_station_english,mrt_line_english,latitude,longitude
0,NS1,Jurong East MRT Station Singapore,North South Line,1.333131,103.742091
1,NS2,Bukit Batok MRT Station Singapore,North South Line,1.348506,103.749222
2,NS3,Bukit Gombak MRT Station Singapore,North South Line,1.358915,103.751831
3,NS4,Choa Chu Kang MRT Station Singapore,North South Line,1.385385,103.744337
4,NS5,Yew Tee MRT Station Singapore,North South Line,1.397329,103.747502

In [78]:
mrt.loc[[115]]

,stn_code,mrt_station_english,mrt_line_english,latitude,longitude
115,DT10,Stevens MRT Station Singapore,Downtown Line,1.319958,103.825943

In [79]:
mrt.to_csv('mrt_location.csv')

# Extracting hawker centre geolocation data

In [108]:
from bs4 import BeautifulSoup as bs

with open('hawker-centres-kml.kml') as data:
    kml_soup = bs(data, 'lxml-xml') # Parse as XML
    
add = []
lat = []
long = []

descriptions = kml_soup.find_all('ExtendedData')
for d in descriptions:
    coord = d.find_all('SimpleData')
    address = coord[0].text
    latitude = coord[3].text
    longitude = coord[8].text
    print(address, latitude,longitude)
    add.append(address)
    lat.append(latitude)
    long.append(longitude)
   
print (len(add),len(lat),len(long))

2, Adam Road, Singapore 289876 1.32413197 103.8141632
Blk 453A, Ang Mo Kio Ave 10, Singapore 561453 1.3682999599999999 103.8564377
Blk 221A/B, Boon Lay Place, Singapore 641221/642221 1.34528005 103.7128525
Blk 353, Clementi Ave 2, Singapore 120353 1.31433797 103.7707748
Blk 448, Clementi Ave 3, Singapore 120448 1.31334996 103.7645874
Blk 7, Empress Road, Singapore 260007 1.31631005 103.805687
Blk 209, Hougang Street 21, Singapore 530209 1.359079 118
Blk 159, Mei Chin Road, Singapore 140159 1.29330003 103.8029633
Blk 630, Bedok Reservoir Road, Singapore 470630 1.33298004 103.9142075
Blk 335, Smith Street, Singapore 050335 1.2823 103.8428802
271, Onan Road, Singapore 424768 1.309412 103.901825
1220, East Coast Parkway, Singapore 468960 1.30772996 103.9343033
Blk 4A, Eunos Crescent, Singapore 402004 1.320292 103.9042206
Blk 69, Geylang Bahru, Singapore 330069 1.32152998 103.8700714
1, Geylang Serai, Singapore 402001 Existing 302
Blk 20, Ghim Moh Road, Singapore 270020 1.31105995 103.7882919
505, Beach Road, Singapore 199583 1.30287397 103.8638763
Blk 13/14, Haig Road, Singapore 430013/430014 1.31518996 103.8956528
Blk 22A/B, Havelock Road, Singapore 161022/162022 1.28804004 103.829689
Blk 117, Aljunied Ave 2, Singapore 380117 1.32070994 103.8870926
5, Cross Street, Singapore 048148 1.28156793 103.8488473
Blk 20/21, Marsiling Lane, Singapore 730020/730021 1.44398999 103.7772598
Blk 4,Woodlands St 12,Singapore 738623 1.433543 103.779881
1, Kadayanallur Street, Singapore 069184 1.28055096 103.8444595
Blk 32, New Market Road, Singapore 050032 1.28487098 103.8425903
Blk 208B, New Upper Changi Road, Singapore 462208 1.3246289999999998 103.930477
Blk 58, New Upper Changi Road, Singapore 461058 1.32516551 103.940155
500, Clemenceau Ave North, Singapore 229495 1.3122249799999999 103.8397293
861, North Bridge Road, Singapore 198783 1.3058470500000001 103.8638611
Blk 51, Old Airport Road, Singapore 390051 1.30827999 103.8858414
Blk 51, Tampines Ave 4, Singapore 529684 1.352983 103.940231
121, Pasir Panjang Road, Singapore 118543 1.27565897 103.7915573
Blk 110, Pasir Ris Central, Singapore 519641 1.373318 103.951364
Blk 270, Queen Street, Singapore 180270 1.30112004 103.8541412
Blk 85, Redhill Lane, Singapore 150085 1.28740001 103.8183975
590, Upper Thomson Road, Singapore 574419 1.37241995 103.8290329
49A, Serangoon Garden Way, Singapore 555945 1.3635400500000001 103.8669815
Blk 320, Shunfu Road, Singapore 570320 1.35181999 103.8370285
National Development Building, Annex B, Telok Ayer Street, Singapore 069111 Existing 1
Blk 226D, Ang Mo Kio Ave 1, Singapore 564226 1.36695004 103.8391876
Blk 341, Ang Mo Kio Ave 1, Singapore 560341 1.36416996 103.84832
Blk 409, Ang Mo Kio Ave 10, Singapore 560409 1.36273003 103.8553772
Blk 527, Ang Mo Kio Ave 10, Singapore 560527 1.37270999 103.8544464
Blk 160/162, Ang Mo Kio Ave 4, Singapore 560160/560162 1.37460005 103.839241
Blk 628, Ang Mo Kio Ave 4, Singapore 560628 1.38066268 103.8407516
Blk 676, Woodlands Drive 71, Singapore 730676 1.440119 103.800735
Blk 84, Marine Parade Central, Singapore 440084 1.30233002 103.9063873
Blk 50A, Marine Terrace, Singapore 441050 1.30580998 103.9157867
Blk 79/79A, Circuit Road, Singapore 370079/371079 1.32666004 103.8851166
Blk 80, Circuit Road, Singapore 370080 1.32790005 103.8871536
Blk 89, Circuit Road, Singapore 370089 1.32363999 103.8855209
Blk 726, Clementi West Street 2, Singapore 120726 1.30391705 103.7641754
31, Commonwealth Crescent, Singapore 149644 1.30743206 103.7994614
Blk 1A/ 2A/ 3A, Commonwealth Drive, Singapore 140001/140002/140003 1.29955006 103.7980194
Blk 6, Jalan Bukit Merah, Singapore 150006 1.28700995 103.8081894
Blk 1, Jalan Kukoh, Singapore 161001 1.28831995 103.8399963
Blk 347, Jurong East Ave 1, Singapore 600347 1.34536004 103.7315826
Blk 254, Jurong East Street 24, Singapore 600254 1.34343302 103.7376862
Blk 50, Jurong West St 61, Singapore 648202 1.3412229999999998 103.697374
Blk 505, Jurong West Street 52, Singapore 640505 1.34969997 103.7184601
17, Old Airport Road, Singapore 397972 1.30711246 103.8841476
166, Jalan Besar, Singapore 208877 1.30733502 103.8568497
Blk 665, Buffalo Road, Singapore 210665 1.30619001 103.8506699
Blk 163, Bukit Merah Central, Singapore 150163 1.28374004 103.8171082
Blk 120, Bukit Merah Lane, Singapore 150120 1.28636003 103.8045502
Blk 115, Bukit Merah View, Singapore 151115 1.28524005 103.8223724
2 Bukit Panjang Ring Road, Singapore 679947 1.378269 103.772432
51 Hougang Avenue 9, Singapore 538776 1.3749377 103.8829472
Blk 37A, Teban Garden Road, Singapore 601037 1.3205173000000001 103.7420807
Blk 11, Telok Blangah Crescent, Singapore 090011 1.27743995 103.8187332
Blk 79, Telok Blangah Drive, Singapore 100079 1.27342999 103.8076782
Blk 82, Telok Blangah Drive, Singapore 100082 1.27398002 103.8079987
Blk 36, Telok Blangah Rise, Singapore 090036 1.27266002 103.8221283
30, Seng Poh Road, Singapore 168898 1.28468299 103.832428
Blk 127, Lorong 1 Toa Payoh, Singapore 310127 1.33816004 103.8447876
Blk 74, Lorong 4 Toa Payoh, Singapore 310074 1.33462 103.8520584
51, Upper Bukit Timah Road, Singapore 588215 1.33964503 103.7758026
Blk 41A, Cambridge Road, Singapore 211041 1.3162000200000001 103.8503036
Blk 724, Ang Mo Kio Ave 6, Singapore 560724 1.37204003 103.8464966
Blk 226H, Ang Mo Kio Street 22, Singapore 568226 1.36726606 103.8399429
1, Bedok Road, Singapore 469572 1.32035303 103.9554749
Blk 216, Bedok North Street 1, Singapore 460216 1.32711995 103.9332962
Blk 511, Bedok North Street 3, Singapore 460511 1.33331001 103.930687
Blk 538, Bedok North Street 3, Singapore 460538 1.3321000299999999 103.9247208
Blk 49, Sims Place, Singapore 380049 1.31710005 103.8793793
3, Yung Sheng Road, Singapore 618499 1.33468103 103.7216187
Blk 137, Tampines Street 11, Singapore 521137 1.34559596 103.9445953
48A, Tanglin Halt Road, Singapore 148813 1.3008500299999999 103.7976837
Blk 6, Tanjong Pagar Plaza, Singapore 081006 1.2766799899999999 103.8432312
Blk 85, Bedok North Street 4, Singapore 460085 1.33205998 103.9388123
Blk 16, Bedok South Road, Singapore 460016 1.32055998 103.9355469
Blk 29, Bendemeer Road, Singapore 330029 1.31928003 103.8630905
38A, Beo Crescent, Singapore 169982 1.28848803 103.8272476
Blk 2/3, Changi Village Road, Singapore 500002/500003 1.38971996 103.9881821
20, Kensington Park Road, Singapore 557269 1.36422801 103.8665314
Blk 93, Lorong 4 Toa Payoh, Singapore 310093 1.33853996 103.8495712
Blk 75, Lorong 5 Toa Payoh, Singapore 310075 1.33609998 103.8529968
Blk 22, Lorong 7 Toa Payoh, Singapore 310022 1.3352899599999999 103.8570633
Blk 210, Lorong 8 Toa Payoh, Singapore 310210 1.34033001 103.8544617
Blk 17, Upper Boon Keng Road, Singapore 380017 1.31508994 103.8716812
Blk 531A, Upper Cross Street, Singapore 051531 1.28446996 103.8458633
Blk 502, West Coast Drive, Singapore 120502 1.3119599800000001 103.7591019
Blk 503, West Coast Drive, Singapore 120503 1.31186998 103.7598038
Blk 90, Whampoa Drive, Singapore 320090 1.32314003 103.8550415
Blk 91/92, Whampoa Drive, Singapore 320091/320092 1.32349002 103.8541336
Blk 51, Yishun Avenue 11, Singapore 768867 1.424911 103.844992
Blk 104/105, Yishun Ring Road, Singapore 760104/760105 1.43165803 103.8280716
70, Zion Road, Singapore 247792 1.29234004 103.8311844
38A #N/A 11/5/2015
202C #N/A 30/6/2017
Blk 79, Redhill Lane, Singapore 150079 1.28790999 103.8183975
Blk 44, Holland Drive, Singapore 270044 1.30818999 103.7928391
1, Lorong Mambong, Singapore 277700 1.31110203 103.7949448
Blk 105, Hougang Ave 1, Singapore 530105 1.35408998 103.890213
Blk 4A, Jalan Batu, Singapore 432004 1.30243003 103.8839798
Blk 112, Jalan Bukit Merah, Singapore 160112 1.2800699500000001 103.8260727
116 116 116

In [118]:
hawker = pd.DataFrame()
hawker['address'] = add
hawker['latitude'] = lat
hawker['longitude'] = long

hawker.head()

,address,latitude,longitude
0,"2, Adam Road, Singapore 289876",1.32413197,103.8141632
1,"Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",1.3682999599999999,103.8564377
2,"Blk 221A/B, Boon Lay Place, Singapore 641221/6...",1.34528005,103.7128525
3,"Blk 353, Clementi Ave 2, Singapore 120353",1.31433797,103.7707748
4,"Blk 448, Clementi Ave 3, Singapore 120448",1.31334996,103.7645874

In [119]:
hawker

,address,latitude,longitude
0,"2, Adam Road, Singapore 289876",1.32413197,103.8141632
1,"Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",1.3682999599999999,103.8564377
2,"Blk 221A/B, Boon Lay Place, Singapore 641221/6...",1.34528005,103.7128525
3,"Blk 353, Clementi Ave 2, Singapore 120353",1.31433797,103.7707748
4,"Blk 448, Clementi Ave 3, Singapore 120448",1.31334996,103.7645874
5,"Blk 7, Empress Road, Singapore 260007",1.31631005,103.805687
6,"Blk 209, Hougang Street 21, Singapore 530209",1.359079,118
7,"Blk 159, Mei Chin Road, Singapore 140159",1.29330003,103.8029633
8,"Blk 630, Bedok Reservoir Road, Singapore 470630",1.33298004,103.9142075
9,"Blk 335, Smith Street, Singapore 050335",1.2823,103.8428802
10,"271, Onan Road, Singapore 424768",1.309412,103.901825
11,"1220, East Coast Parkway, Singapore 468960",1.30772996,103.9343033
12,"Blk 4A, Eunos Crescent, Singapore 402004",1.320292,103.9042206
13,"Blk 69, Geylang Bahru, Singapore 330069",1.32152998,103.8700714
14,"1, Geylang Serai, Singapore 402001",Existing,302
15,"Blk 20, Ghim Moh Road, Singapore 270020",1.31105995,103.7882919
16,"505, Beach Road, Singapore 199583",1.30287397,103.8638763
17,"Blk 13/14, Haig Road, Singapore 430013/430014",1.31518996,103.8956528
18,"Blk 22A/B, Havelock Road, Singapore 161022/162022",1.28804004,103.829689
19,"Blk 117, Aljunied Ave 2, Singapore 380117",1.32070994,103.8870926
20,"5, Cross Street, Singapore 048148",1.28156793,103.8488473
21,"Blk 20/21, Marsiling Lane, Singapore 730020/73...",1.44398999,103.7772598
22,"Blk 4,Woodlands St 12,Singapore 738623",1.433543,103.779881
23,"1, Kadayanallur Street, Singapore 069184",1.28055096,103.8444595
24,"Blk 32, New Market Road, Singapore 050032",1.28487098,103.8425903
25,"Blk 208B, New Upper Changi Road, Singapore 462208",1.3246289999999998,103.930477
26,"Blk 58, New Upper Changi Road, Singapore 461058",1.32516551,103.940155
27,"500, Clemenceau Ave North, Singapore 229495",1.3122249799999999,103.8397293
28,"861, North Bridge Road, Singapore 198783",1.3058470500000001,103.8638611
29,"Blk 51, Old Airport Road, Singapore 390051",1.30827999,103.8858414
...,...,...,...
86,"Blk 137, Tampines Street 11, Singapore 521137",1.34559596,103.9445953
87,"48A, Tanglin Halt Road, Singapore 148813",1.3008500299999999,103.7976837
88,"Blk 6, Tanjong Pagar Plaza, Singapore 081006",1.2766799899999999,103.8432312
89,"Blk 85, Bedok North Street 4, Singapore 460085",1.33205998,103.9388123
90,"Blk 16, Bedok South Road, Singapore 460016",1.32055998,103.9355469
91,"Blk 29, Bendemeer Road, Singapore 330029",1.31928003,103.8630905
92,"38A, Beo Crescent, Singapore 169982",1.28848803,103.8272476
93,"Blk 2/3, Changi Village Road, Singapore 500002...",1.38971996,103.9881821
94,"20, Kensington Park Road, Singapore 557269",1.36422801,103.8665314
95,"Blk 93, Lorong 4 Toa Payoh, Singapore 310093",1.33853996,103.8495712
96,"Blk 75, Lorong 5 Toa Payoh, Singapore 310075",1.33609998,103.8529968
97,"Blk 22, Lorong 7 Toa Payoh, Singapore 310022",1.3352899599999999,103.8570633
98,"Blk 210, Lorong 8 Toa Payoh, Singapore 310210",1.34033001,103.8544617
99,"Blk 17, Upper Boon Keng Road, Singapore 380017",1.31508994,103.8716812
100,"Blk 531A, Upper Cross Street, Singapore 051531",1.28446996,103.8458633
101,"Blk 502, West Coast Drive, Singapore 120502",1.3119599800000001,103.7591019
102,"Blk 503, West Coast Drive, Singapore 120503",1.31186998,103.7598038
103,"Blk 90, Whampoa Drive, Singapore 320090",1.32314003,103.8550415
104,"Blk 91/92, Whampoa Drive, Singapore 320091/320092",1.32349002,103.8541336
105,"Blk 51, Yishun Avenue 11, Singapore 768867",1.424911,103.844992
106,"Blk 104/105, Yishun Ring Road, Singapore 76010...",1.43165803,103.8280716
107,"70, Zion Road, Singapore 247792",1.29234004,103.8311844
108,38A,#N/A,11/5/2015
109,202C,#N/A,30/6/2017
110,"Blk 79, Redhill Lane, Singapore 150079",1.28790999,103.8183975
111,"Blk 44, Holland Drive, Singapore 270044",1.30818999,103.7928391
112,"1, Lorong Mambong, Singapore 277700",1.31110203,103.7949448
113,"Blk 105, Hougang Ave 1, Singapore 530105",1.35408998,103.890213
114,"Blk 4A, Jalan Batu, Singapore 432004",1.30243003,103.8839798
115,"Blk 112, Jalan Bukit Merah, Singapore 160112",1.2800699500000001,103.8260727

In [121]:
hawker = hawker.drop(hawker.index[6])
hawker = hawker.reset_index(drop=True)
hawker

,address,latitude,longitude
0,"2, Adam Road, Singapore 289876",1.32413197,103.8141632
1,"Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",1.3682999599999999,103.8564377
2,"Blk 221A/B, Boon Lay Place, Singapore 641221/6...",1.34528005,103.7128525
3,"Blk 353, Clementi Ave 2, Singapore 120353",1.31433797,103.7707748
4,"Blk 448, Clementi Ave 3, Singapore 120448",1.31334996,103.7645874
5,"Blk 7, Empress Road, Singapore 260007",1.31631005,103.805687
6,"Blk 159, Mei Chin Road, Singapore 140159",1.29330003,103.8029633
7,"Blk 630, Bedok Reservoir Road, Singapore 470630",1.33298004,103.9142075
8,"Blk 335, Smith Street, Singapore 050335",1.2823,103.8428802
9,"271, Onan Road, Singapore 424768",1.309412,103.901825
10,"1220, East Coast Parkway, Singapore 468960",1.30772996,103.9343033
11,"Blk 4A, Eunos Crescent, Singapore 402004",1.320292,103.9042206
12,"Blk 69, Geylang Bahru, Singapore 330069",1.32152998,103.8700714
13,"1, Geylang Serai, Singapore 402001",Existing,302
14,"Blk 20, Ghim Moh Road, Singapore 270020",1.31105995,103.7882919
15,"505, Beach Road, Singapore 199583",1.30287397,103.8638763
16,"Blk 13/14, Haig Road, Singapore 430013/430014",1.31518996,103.8956528
17,"Blk 22A/B, Havelock Road, Singapore 161022/162022",1.28804004,103.829689
18,"Blk 117, Aljunied Ave 2, Singapore 380117",1.32070994,103.8870926
19,"5, Cross Street, Singapore 048148",1.28156793,103.8488473
20,"Blk 20/21, Marsiling Lane, Singapore 730020/73...",1.44398999,103.7772598
21,"Blk 4,Woodlands St 12,Singapore 738623",1.433543,103.779881
22,"1, Kadayanallur Street, Singapore 069184",1.28055096,103.8444595
23,"Blk 32, New Market Road, Singapore 050032",1.28487098,103.8425903
24,"Blk 208B, New Upper Changi Road, Singapore 462208",1.3246289999999998,103.930477
25,"Blk 58, New Upper Changi Road, Singapore 461058",1.32516551,103.940155
26,"500, Clemenceau Ave North, Singapore 229495",1.3122249799999999,103.8397293
27,"861, North Bridge Road, Singapore 198783",1.3058470500000001,103.8638611
28,"Blk 51, Old Airport Road, Singapore 390051",1.30827999,103.8858414
29,"Blk 51, Tampines Ave 4, Singapore 529684",1.352983,103.940231
...,...,...,...
85,"Blk 137, Tampines Street 11, Singapore 521137",1.34559596,103.9445953
86,"48A, Tanglin Halt Road, Singapore 148813",1.3008500299999999,103.7976837
87,"Blk 6, Tanjong Pagar Plaza, Singapore 081006",1.2766799899999999,103.8432312
88,"Blk 85, Bedok North Street 4, Singapore 460085",1.33205998,103.9388123
89,"Blk 16, Bedok South Road, Singapore 460016",1.32055998,103.9355469
90,"Blk 29, Bendemeer Road, Singapore 330029",1.31928003,103.8630905
91,"38A, Beo Crescent, Singapore 169982",1.28848803,103.8272476
92,"Blk 2/3, Changi Village Road, Singapore 500002...",1.38971996,103.9881821
93,"20, Kensington Park Road, Singapore 557269",1.36422801,103.8665314
94,"Blk 93, Lorong 4 Toa Payoh, Singapore 310093",1.33853996,103.8495712
95,"Blk 75, Lorong 5 Toa Payoh, Singapore 310075",1.33609998,103.8529968
96,"Blk 22, Lorong 7 Toa Payoh, Singapore 310022",1.3352899599999999,103.8570633
97,"Blk 210, Lorong 8 Toa Payoh, Singapore 310210",1.34033001,103.8544617
98,"Blk 17, Upper Boon Keng Road, Singapore 380017",1.31508994,103.8716812
99,"Blk 531A, Upper Cross Street, Singapore 051531",1.28446996,103.8458633
100,"Blk 502, West Coast Drive, Singapore 120502",1.3119599800000001,103.7591019
101,"Blk 503, West Coast Drive, Singapore 120503",1.31186998,103.7598038
102,"Blk 90, Whampoa Drive, Singapore 320090",1.32314003,103.8550415
103,"Blk 91/92, Whampoa Drive, Singapore 320091/320092",1.32349002,103.8541336
104,"Blk 51, Yishun Avenue 11, Singapore 768867",1.424911,103.844992
105,"Blk 104/105, Yishun Ring Road, Singapore 76010...",1.43165803,103.8280716
106,"70, Zion Road, Singapore 247792",1.29234004,103.8311844
107,38A,#N/A,11/5/2015
108,202C,#N/A,30/6/2017
109,"Blk 79, Redhill Lane, Singapore 150079",1.28790999,103.8183975
110,"Blk 44, Holland Drive, Singapore 270044",1.30818999,103.7928391
111,"1, Lorong Mambong, Singapore 277700",1.31110203,103.7949448
112,"Blk 105, Hougang Ave 1, Singapore 530105",1.35408998,103.890213
113,"Blk 4A, Jalan Batu, Singapore 432004",1.30243003,103.8839798
114,"Blk 112, Jalan Bukit Merah, Singapore 160112",1.2800699500000001,103.8260727

In [122]:
hawker = hawker.drop(hawker.index[13])
hawker = hawker.reset_index(drop=True)
hawker

,address,latitude,longitude
0,"2, Adam Road, Singapore 289876",1.32413197,103.8141632
1,"Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",1.3682999599999999,103.8564377
2,"Blk 221A/B, Boon Lay Place, Singapore 641221/6...",1.34528005,103.7128525
3,"Blk 353, Clementi Ave 2, Singapore 120353",1.31433797,103.7707748
4,"Blk 448, Clementi Ave 3, Singapore 120448",1.31334996,103.7645874
5,"Blk 7, Empress Road, Singapore 260007",1.31631005,103.805687
6,"Blk 159, Mei Chin Road, Singapore 140159",1.29330003,103.8029633
7,"Blk 630, Bedok Reservoir Road, Singapore 470630",1.33298004,103.9142075
8,"Blk 335, Smith Street, Singapore 050335",1.2823,103.8428802
9,"271, Onan Road, Singapore 424768",1.309412,103.901825
10,"1220, East Coast Parkway, Singapore 468960",1.30772996,103.9343033
11,"Blk 4A, Eunos Crescent, Singapore 402004",1.320292,103.9042206
12,"Blk 69, Geylang Bahru, Singapore 330069",1.32152998,103.8700714
13,"Blk 20, Ghim Moh Road, Singapore 270020",1.31105995,103.7882919
14,"505, Beach Road, Singapore 199583",1.30287397,103.8638763
15,"Blk 13/14, Haig Road, Singapore 430013/430014",1.31518996,103.8956528
16,"Blk 22A/B, Havelock Road, Singapore 161022/162022",1.28804004,103.829689
17,"Blk 117, Aljunied Ave 2, Singapore 380117",1.32070994,103.8870926
18,"5, Cross Street, Singapore 048148",1.28156793,103.8488473
19,"Blk 20/21, Marsiling Lane, Singapore 730020/73...",1.44398999,103.7772598
20,"Blk 4,Woodlands St 12,Singapore 738623",1.433543,103.779881
21,"1, Kadayanallur Street, Singapore 069184",1.28055096,103.8444595
22,"Blk 32, New Market Road, Singapore 050032",1.28487098,103.8425903
23,"Blk 208B, New Upper Changi Road, Singapore 462208",1.3246289999999998,103.930477
24,"Blk 58, New Upper Changi Road, Singapore 461058",1.32516551,103.940155
25,"500, Clemenceau Ave North, Singapore 229495",1.3122249799999999,103.8397293
26,"861, North Bridge Road, Singapore 198783",1.3058470500000001,103.8638611
27,"Blk 51, Old Airport Road, Singapore 390051",1.30827999,103.8858414
28,"Blk 51, Tampines Ave 4, Singapore 529684",1.352983,103.940231
29,"121, Pasir Panjang Road, Singapore 118543",1.27565897,103.7915573
...,...,...,...
84,"Blk 137, Tampines Street 11, Singapore 521137",1.34559596,103.9445953
85,"48A, Tanglin Halt Road, Singapore 148813",1.3008500299999999,103.7976837
86,"Blk 6, Tanjong Pagar Plaza, Singapore 081006",1.2766799899999999,103.8432312
87,"Blk 85, Bedok North Street 4, Singapore 460085",1.33205998,103.9388123
88,"Blk 16, Bedok South Road, Singapore 460016",1.32055998,103.9355469
89,"Blk 29, Bendemeer Road, Singapore 330029",1.31928003,103.8630905
90,"38A, Beo Crescent, Singapore 169982",1.28848803,103.8272476
91,"Blk 2/3, Changi Village Road, Singapore 500002...",1.38971996,103.9881821
92,"20, Kensington Park Road, Singapore 557269",1.36422801,103.8665314
93,"Blk 93, Lorong 4 Toa Payoh, Singapore 310093",1.33853996,103.8495712
94,"Blk 75, Lorong 5 Toa Payoh, Singapore 310075",1.33609998,103.8529968
95,"Blk 22, Lorong 7 Toa Payoh, Singapore 310022",1.3352899599999999,103.8570633
96,"Blk 210, Lorong 8 Toa Payoh, Singapore 310210",1.34033001,103.8544617
97,"Blk 17, Upper Boon Keng Road, Singapore 380017",1.31508994,103.8716812
98,"Blk 531A, Upper Cross Street, Singapore 051531",1.28446996,103.8458633
99,"Blk 502, West Coast Drive, Singapore 120502",1.3119599800000001,103.7591019
100,"Blk 503, West Coast Drive, Singapore 120503",1.31186998,103.7598038
101,"Blk 90, Whampoa Drive, Singapore 320090",1.32314003,103.8550415
102,"Blk 91/92, Whampoa Drive, Singapore 320091/320092",1.32349002,103.8541336
103,"Blk 51, Yishun Avenue 11, Singapore 768867",1.424911,103.844992
104,"Blk 104/105, Yishun Ring Road, Singapore 76010...",1.43165803,103.8280716
105,"70, Zion Road, Singapore 247792",1.29234004,103.8311844
106,38A,#N/A,11/5/2015
107,202C,#N/A,30/6/2017
108,"Blk 79, Redhill Lane, Singapore 150079",1.28790999,103.8183975
109,"Blk 44, Holland Drive, Singapore 270044",1.30818999,103.7928391
110,"1, Lorong Mambong, Singapore 277700",1.31110203,103.7949448
111,"Blk 105, Hougang Ave 1, Singapore 530105",1.35408998,103.890213
112,"Blk 4A, Jalan Batu, Singapore 432004",1.30243003,103.8839798
113,"Blk 112, Jalan Bukit Merah, Singapore 160112",1.2800699500000001,103.8260727

In [124]:
hawker = hawker.drop(hawker.index[106])
hawker = hawker.reset_index(drop=True)
hawker

,address,latitude,longitude
0,"2, Adam Road, Singapore 289876",1.32413197,103.8141632
1,"Blk 453A, Ang Mo Kio Ave 10, Singapore 561453",1.3682999599999999,103.8564377
2,"Blk 221A/B, Boon Lay Place, Singapore 641221/6...",1.34528005,103.7128525
3,"Blk 353, Clementi Ave 2, Singapore 120353",1.31433797,103.7707748
4,"Blk 448, Clementi Ave 3, Singapore 120448",1.31334996,103.7645874
5,"Blk 7, Empress Road, Singapore 260007",1.31631005,103.805687
6,"Blk 159, Mei Chin Road, Singapore 140159",1.29330003,103.8029633
7,"Blk 630, Bedok Reservoir Road, Singapore 470630",1.33298004,103.9142075
8,"Blk 335, Smith Street, Singapore 050335",1.2823,103.8428802
9,"271, Onan Road, Singapore 424768",1.309412,103.901825
10,"1220, East Coast Parkway, Singapore 468960",1.30772996,103.9343033
11,"Blk 4A, Eunos Crescent, Singapore 402004",1.320292,103.9042206
12,"Blk 69, Geylang Bahru, Singapore 330069",1.32152998,103.8700714
13,"Blk 20, Ghim Moh Road, Singapore 270020",1.31105995,103.7882919
14,"505, Beach Road, Singapore 199583",1.30287397,103.8638763
15,"Blk 13/14, Haig Road, Singapore 430013/430014",1.31518996,103.8956528
16,"Blk 22A/B, Havelock Road, Singapore 161022/162022",1.28804004,103.829689
17,"Blk 117, Aljunied Ave 2, Singapore 380117",1.32070994,103.8870926
18,"5, Cross Street, Singapore 048148",1.28156793,103.8488473
19,"Blk 20/21, Marsiling Lane, Singapore 730020/73...",1.44398999,103.7772598
20,"Blk 4,Woodlands St 12,Singapore 738623",1.433543,103.779881
21,"1, Kadayanallur Street, Singapore 069184",1.28055096,103.8444595
22,"Blk 32, New Market Road, Singapore 050032",1.28487098,103.8425903
23,"Blk 208B, New Upper Changi Road, Singapore 462208",1.3246289999999998,103.930477
24,"Blk 58, New Upper Changi Road, Singapore 461058",1.32516551,103.940155
25,"500, Clemenceau Ave North, Singapore 229495",1.3122249799999999,103.8397293
26,"861, North Bridge Road, Singapore 198783",1.3058470500000001,103.8638611
27,"Blk 51, Old Airport Road, Singapore 390051",1.30827999,103.8858414
28,"Blk 51, Tampines Ave 4, Singapore 529684",1.352983,103.940231
29,"121, Pasir Panjang Road, Singapore 118543",1.27565897,103.7915573
...,...,...,...
82,"Blk 49, Sims Place, Singapore 380049",1.31710005,103.8793793
83,"3, Yung Sheng Road, Singapore 618499",1.33468103,103.7216187
84,"Blk 137, Tampines Street 11, Singapore 521137",1.34559596,103.9445953
85,"48A, Tanglin Halt Road, Singapore 148813",1.3008500299999999,103.7976837
86,"Blk 6, Tanjong Pagar Plaza, Singapore 081006",1.2766799899999999,103.8432312
87,"Blk 85, Bedok North Street 4, Singapore 460085",1.33205998,103.9388123
88,"Blk 16, Bedok South Road, Singapore 460016",1.32055998,103.9355469
89,"Blk 29, Bendemeer Road, Singapore 330029",1.31928003,103.8630905
90,"38A, Beo Crescent, Singapore 169982",1.28848803,103.8272476
91,"Blk 2/3, Changi Village Road, Singapore 500002...",1.38971996,103.9881821
92,"20, Kensington Park Road, Singapore 557269",1.36422801,103.8665314
93,"Blk 93, Lorong 4 Toa Payoh, Singapore 310093",1.33853996,103.8495712
94,"Blk 75, Lorong 5 Toa Payoh, Singapore 310075",1.33609998,103.8529968
95,"Blk 22, Lorong 7 Toa Payoh, Singapore 310022",1.3352899599999999,103.8570633
96,"Blk 210, Lorong 8 Toa Payoh, Singapore 310210",1.34033001,103.8544617
97,"Blk 17, Upper Boon Keng Road, Singapore 380017",1.31508994,103.8716812
98,"Blk 531A, Upper Cross Street, Singapore 051531",1.28446996,103.8458633
99,"Blk 502, West Coast Drive, Singapore 120502",1.3119599800000001,103.7591019
100,"Blk 503, West Coast Drive, Singapore 120503",1.31186998,103.7598038
101,"Blk 90, Whampoa Drive, Singapore 320090",1.32314003,103.8550415
102,"Blk 91/92, Whampoa Drive, Singapore 320091/320092",1.32349002,103.8541336
103,"Blk 51, Yishun Avenue 11, Singapore 768867",1.424911,103.844992
104,"Blk 104/105, Yishun Ring Road, Singapore 76010...",1.43165803,103.8280716
105,"70, Zion Road, Singapore 247792",1.29234004,103.8311844
106,"Blk 79, Redhill Lane, Singapore 150079",1.28790999,103.8183975
107,"Blk 44, Holland Drive, Singapore 270044",1.30818999,103.7928391
108,"1, Lorong Mambong, Singapore 277700",1.31110203,103.7949448
109,"Blk 105, Hougang Ave 1, Singapore 530105",1.35408998,103.890213
110,"Blk 4A, Jalan Batu, Singapore 432004",1.30243003,103.8839798
111,"Blk 112, Jalan Bukit Merah, Singapore 160112",1.2800699500000001,103.8260727

In [125]:
hawker.to_csv('hawker_centre_location.csv')